<?php declare(strict_types = 1);

namespace Netmosfera\Opal\InternalTools;

use Netmosfera\Opal\PackageComponent;
use Netmosfera\Opal\PackagePath;
use Netmosfera\Opal\Path;
use const DIRECTORY_SEPARATOR as DS;
use function Netmosfera\Opal\Files\readDirectory;

function preprocessStaticComponents(
    Array $packagePaths,
    Array $preprocessors,
    Path $compileDirectory,
    Bool $executeIt,
    ?Int $directoryPermissions,
    ?Int $filePermissions
){
    $components = [];
    /** @var PackageComponent[] $components */

    foreach($packagePaths as $packagePath){
        assert($packagePath instanceof PackagePath);
        foreach(readDirectory($packagePath->path) as $filePath){
            $component = componentFromPath($packagePath, $filePath);
            if($component !== NULL && $component->extensions === ".inc.php"){
                preprocessComponent(
                    $packagePath, $component, $preprocessors, $compileDirectory,
                    FALSE, $directoryPermissions, $filePermissions
                );
                $components[] = $component->absolutePath;
            }
        }
    }

    $staticInclusionsSource = "<?php\n\n";
    $staticInclusionsSource .= "// Generated by netmosfera/opal.\n";
    $staticInclusionsSource .= "// Do not edit this file manually!\n ";
    $staticInclusionsSource .= "\n";

    foreach($components as $component){
        $fileString = var_export($component, TRUE);
        $staticInclusionsSource .= "require __DIR__ . " . $fileString . ";\n";
    }

    $destinationFile = $compileDirectory->path . DS . "static-inclusions.php";

    file_put_contents($destinationFile, $staticInclusionsSource);

    if($executeIt){
        (function($__OPAL_FILE__){
            require $__OPAL_FILE__;
        })($destinationFile);
    }
}
